// A single source of truth for all the site related data
export const siteData = {
  KnowESR1: {
    live: {
      pages: [
        {
          page: "home",
          path: "/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".navigatinBar", state: [], captureType: "normal", floating: false },
            { section: "Share story", selector: ".shareStory", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: "#sec1", state: [], captureType: "normal", floating: false },
            { section: "About", selector: "#About", state: [], captureType: "normal", floating: false },
            { section: "Impact", selector: "#Impact", state: [], captureType: "normal", floating: false },
            { section: "Impact2", selector: "#Impact_2", state: [], captureType: "normal", floating: false },
            { section: "Testing", selector: "#Testing", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: "#footer-container", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "resources",
          path: "/resources.html#video_library",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".navigatinBar", state: [], captureType: "normal", floating: false },
            { section: "Share story", selector: ".shareStory", state: [], captureType: "normal", floating: false },
            { section: "Video Library", selector: "#Video_library", state: [], captureType: "normal", floating: false },
            { section: "Brochure", selector: "#Educational_brochure", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: "#footer-container", state: [], captureType: "normal", floating: false },
          ],
        },
      ],
    },
    staging: {
      pages: [
        {
          page: "home",
          path: "/index.html",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".navigatinBar", state: [], captureType: "normal", floating: false },
            { section: "Share story", selector: ".shareStory", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: "#sec1", state: [], captureType: "normal", floating: false },
            { section: "About", selector: "#About", state: [], captureType: "normal", floating: false },
            { section: "Impact", selector: "#Impact", state: [], captureType: "normal", floating: false },
            { section: "Impact2", selector: "#Impact_2", state: [], captureType: "normal", floating: false },
            { section: "Testing", selector: "#Testing", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: "#footer-container", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "resources",
          path: "/resources.html#video_library",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".navigatinBar", state: [], captureType: "normal", floating: false },
            { section: "Share story", selector: ".shareStory", state: [], captureType: "normal", floating: false },
            { section: "Video Library", selector: "#Video_library", state: [], captureType: "normal", floating: false },
            { section: "Discussion Guide", selector: "#Doctor_discussion_guide_parent", state: [], captureType: "normal", floating: false },
            { section: "Brochure", selector: "#Educational_brochure", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: "#footer-container", state: [], captureType: "normal", floating: false },
          ],
        },
      ],
    },
  },

  Elzonris: {
    live: {
      pages: [
        {
          page: "home",
          path: "/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".wp-hero", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: ".main", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "understanding_bpdcn",
          path: "/understanding-bpdcn",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "diagnosis",
          path: "/diagnosis",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.diagnosis", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "about_elzonris",
          path: "/about-elzonris",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "goals",
          path: "/goals-of-treatment",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid.goals-of-treatment", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "what_to_expect",
          path: "/what-to-expect-on-elzonris",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "about_side_effects",
          path: "/about-side-effects",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "resources",
          path: "/resources",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "downloadable_materials",
          path: "/downloadable-materials",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "connection",
          path: "/connection",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
      ],
    },
    staging: {
      pages: [
        {
          page: "home",
          path: "/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".wp-hero", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: ".main", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "understanding_bpdcn",
          path: "/understanding-bpdcn",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "diagnosis",
          path: "/diagnosis",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.diagnosis", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "about_elzonris",
          path: "/about-elzonris",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "goals",
          path: "/goals-of-treatment",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid.goals-of-treatment", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "what_to_expect",
          path: "/what-to-expect-on-elzonris",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "about_side_effects",
          path: "/about-side-effects",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "resources",
          path: "/resources",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "downloadable_materials",
          path: "/downloadable-materials",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "connection",
          path: "/connection",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: "#header", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".page.container-fluid", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: "#sticky-isi", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".footer", state: [], captureType: "normal", floating: false },
          ],
        },
      ],
    },
  },

  TestESR: {
    live: {
      pages: [
        {
          page: "Home",
          path: "/",
          scrollIsWindow: true,
          scrollRoot:null,
          sections: [
            { section: "Home content", selector: ".home_content", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: ".home_footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "How to test for ESR1m",
          path: "/how_to_test",
          scrollIsWindow: false,
          scrollRoot: ".wrapper",
          sections: [
            { section: "Header", selector: ".header_container", state: [], captureType: "normal", floating: false },
            { section: "Test page content", selector: ".test_page_bg_container", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: ".home_footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Importance of ESR1m",
          path: "/ESR1_mutation",
          scrollIsWindow: false,
          scrollRoot: ".wrapper",
          sections: [
            { section: "Header", selector: ".header_container", state: [], captureType: "normal", floating: false },
            {
              section: "Mutation page content",
              selector: ".mutation_page_bg_container",
              state: [],
              captureType: "normal",
              floating: false,
            },
            { section: "Footer", selector: ".home_footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Hear from experts",
          path: "/experts",
          scrollIsWindow: false,
          scrollRoot: ".wrapper",
          sections: [
            { section: "Header", selector: ".header_container", state: [], captureType: "normal", floating: false },
            {
              section: "Expert page content",
              selector: ".expert_page_bg_container",
              state: [],
              captureType: "normal",
              floating: false,
            },
            { section: "Footer", selector: ".home_footer", state: [], captureType: "normal", floating: false },
          ],
        },
      ],
    },
    staging: {
      pages: [
        {
          page: "Home",
          path: "/index.html",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Home content", selector: ".home_content", state: [], captureType: "normal", floating: false },

            { section: "Footer", selector: ".home_footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "How to test for ESR1m",
          path: "/how_to_test.html",
          scrollIsWindow: false,
          scrollRoot: ".wrapper",
          sections: [
            { section: "Header", selector: ".header_container", state: [], captureType: "normal", floating: false },
            { section: "Test page content", selector: ".test_page_bg_container", state: [], captureType: "normal", floating: false },
            { section: "Footer", selector: ".home_footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Importance of ESR1m",
          path: "/ESR1_mutation.html",
          scrollIsWindow: false,
          scrollRoot: ".wrapper",
          sections: [
            { section: "Header", selector: ".header_container", state: [], captureType: "normal", floating: false },
            {
              section: "Mutation page content",
              selector: ".mutation_page_bg_container",
              state: [],
              captureType: "normal",
              floating: false,
            },
            { section: "Footer", selector: ".home_footer", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Hear from experts",
          path: "/experts.html",
          scrollIsWindow: false,
          scrollRoot: ".wrapper",
          sections: [
            { section: "Header", selector: ".header_container", state: [], captureType: "normal", floating: false },
            {
              section: "Expert page content",
              selector: ".expert_page_bg_container",
              state: [],
              captureType: "normal",
              floating: false,
            },
            { section: "Footer", selector: ".home_footer", state: [], captureType: "normal", floating: false },
          ],
        },
      ],
    },
  },

  Orserdu: {
    live: {
      pages: [
        {
          page: "home",
          path: "/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".via-dark_green", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-black.font-light", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Understanding your cancer",
          path: "/understanding-esr1-mutations/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Testing",
          path: "/testing/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Results",
          path: "/orserdu-results/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Safety",
          path: "/orserdu-safety/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Taking Orserdu",
          path: "/taking-orserdu/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Savings and Support",
          path: "/savings-and-support/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "1 stories",
          path: "/real-stories/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black.mt-1", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
      ],
    },
    staging: {
      pages: [
        {
          page: "home",
          path: "/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".via-dark_green", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-black.font-light", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Understanding your cancer",
          path: "/understanding-esr1-mutations/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Testing",
          path: "/testing/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Results",
          path: "/orserdu-results/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Safety",
          path: "/orserdu-safety/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Taking Orserdu",
          path: "/taking-orserdu/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "Savings and Support",
          path: "/savings-and-support/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
        {
          page: "1 stories",
          path: "/real-stories/",
          scrollIsWindow: true,
          scrollRoot: null,
          sections: [
            { section: "Header", selector: ".nav", state: [], captureType: "normal", floating: false },
            { section: "Hero", selector: ".bg-light_mint_green ", state: [], captureType: "normal", floating: false },
            { section: "Info", selector: ".-mt-8", state: [], captureType: "normal", floating: false },
            { section: "Abbrevation", selector: ".text-left.text-black.mt-1", state: [], captureType: "normal", floating: false },
            { section: "ISI", selector: "#isi", state: [], captureType: "normal", floating: false },
            { section: "Sticky ISI", selector: ".fixed.justify-center.flex-col", state: [], captureType: "fixed", floating: true },
            { section: "Footer", selector: ".bg-light_gray ", state: [], captureType: "normal", floating: false },
          ],
        },
      ],
    },
  },
};
